fix(tests): deal with python 3.5
before this commit tests were failing on python 3.5 because of json encoding
> TypeError: the JSON object must be str, not 'bytes'